TaskManagement/Models/Project.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace TaskManagement.Models {
    public class Project {

        public int Id { get; set; }

        [Required]
        public string ProjectCode { get; set; }

        [Required]
        public string ProjectName { get; set; }

        public string UserId { get; set; }

        public virtual ApplicationUser User { get; set; }

        public virtual List<Tasks> Tasks { get; set; }

        public Project() { }

    }
}

TaskManagement/ViewModels/ProjectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TaskManagement.Models;

namespace TaskManagement.ViewModels
{
    public class ProjectViewModel
    {
        public Project Project { get; set; }
        public IEnumerable<SelectListItem> UsersSelectList { get; set; }
        public float Progress { get; set; }


        //CONSTRUCTORS:
        public ProjectViewModel(){}

        public ProjectViewModel(Project project, IEnumerable<SelectListItem> usersSelectlist)
        {
            this.Project = project;
            this.UsersSelectList = usersSelectlist;
        }
        public ProjectViewModel(IEnumerable<SelectListItem> usersSelectlist)
        {
            this.UsersSelectList = usersSelectlist;
        }
        public ProjectViewModel(Project project, float progress)
        {
            this.Project = project;
            this.Progress = progress;
        }

    }
}

TaskManagement/Controllers/ProjectsController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using TaskManagement.Models;
using TaskManagement.Utilities;
using TaskManagement.Buisness;
using TaskManagement.ViewModels;

namespace TaskManagement.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {

        // GET: Projects
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Index()
        {

            //Returning list of Projects and passing it to View
            var projects = DbManager.GetProjects();

            return View(projects);
        }


        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult ListOfSuccessesWithId(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var project = DbManager.GetProjectById(id.Value);
            var progress = DbManager.GetProjectProgress(id.Value);
            var viewModel = new ProjectViewModel(project, progress);

            return View(viewModel);
        }

        // GET: Projects/Details/5
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Details(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Selecting project with specific Id
            var project = DbManager.GetProjectById(Id.Value);

            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Create()
        {
            var rolesList = new List<String>();
            rolesList.Add("Project Manager");
            var usersSelectList = DbManager.GetUsersSelectList(rolesList);

            var viewModel = new ProjectViewModel(usersSelectList);

            return View(viewModel);
        }

        // POST: Projects/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Create(ProjectViewModel projectViewModel)
        {
            var project = DbManager.GetProjectByProjectCode(projectViewModel.Project.ProjectCode);
            
            if (project != null)
            {
                ModelState.AddModelError("Project.ProjectCode", "Project code allready exists!");
            }

            if (ModelState.IsValid)
            {
                //Getting values from text fields and adding them into DB
                DbManager.AddProject(projectViewModel.Project);
                return RedirectToAction("Index");

            }
            var rolesList = new List<String>();
            rolesList.Add("Project Manager");
            projectViewModel.UsersSelectList = DbManager.GetUsersSelectList(rolesList);
            return View(projectViewModel);
        }

        // GET: Projects/Edit/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Project project = DbManager.GetProjectById(id.Value);
            if (project == null)
            {
                return HttpNotFound();
            }
            var rolesList = new List<String>();
            rolesList.Add("Project Manager");
            var usersSelectList = DbManager.GetUsersSelectList(rolesList);

            var viewModel = new ProjectViewModel(project, usersSelectList);

            return View(viewModel);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(ProjectViewModel projectViewModel)
        {
            var project = DbManager.GetProjectByProjectCode(projectViewModel.Project.ProjectCode);

            if (project != null)
            {
                ModelState.AddModelError("Project.ProjectCode", "Project code allready exists!");
            }
            if (ModelState.IsValid)
            {
                DbManager.EditProject(projectViewModel.Project);
                return RedirectToAction("Index");
            }

            var rolesList = new List<String>();
            rolesList.Add("Project Manager");
            projectViewModel.UsersSelectList = DbManager.GetUsersSelectList(rolesList);
            return View(projectViewModel);
        }

        // GET: Projects/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Selecting specific project from DB
            Project project = DbManager.GetProjectById(id.Value);

            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(Project project)
        {

            //Selecting specific project from DB and deleting it from DB
            DbManager.DeleteProject(project);

            return RedirectToAction("Index");
        }

    }
}

TaskManagement/Views/Projects/Create.cshtml
@model TaskManagement.ViewModels.ProjectViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Project.ProjectCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Project.ProjectCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Project.ProjectCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Project.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Project.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Project.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Project.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Project.UserId, Model.UsersSelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Project.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TaskManagement/Views/Projects/Delete.cshtml
@model TaskManagement.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Project code:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectCode)
        </dd>

        <dt>
            Project name:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            Username:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TaskManagement/Views/Projects/Details.cshtml
@model TaskManagement.Models.Project

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Project</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Project code:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectCode)
        </dd>

        <dt>
            Project name:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProjectName)
        </dd>

        <dt>
            User name:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

    </dl>
</div>
<p>
    @if (User.IsInRole("Administrator")) {

        @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
    }

    | @Html.ActionLink("Back to List", "Index")
</p>

TaskManagement/Views/Projects/Edit.cshtml
@model TaskManagement.ViewModels.ProjectViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => Model.Project.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Project.ProjectCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Project.ProjectCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Project.ProjectCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Project.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Project.ProjectName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Project.ProjectName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Project.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Project.UserId, Model.UsersSelectList, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Project.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TaskManagement/Views/Projects/Index.cshtml
@using TaskManagement.Buisness;

@model IEnumerable<TaskManagement.Models.Project>

@{
    ViewBag.Title = "Index";
}

<h2 class="text-center">List of projects</h2>

<p>
    @Html.ActionLink("New project", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ProjectCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        <th>
            Success
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.ActionLink(item.ProjectCode, "ListOfSuccessesWithId", "Projects", new { id = item.Id }, null)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProjectName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.UserName)
            </td>
            <td>
                @DbManager.GetProjectProgress(item.Id) %
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })

                @if (User.IsInRole("Administrator"))
                {
                    <text>|</text>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id })
                    <text>|</text>
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })

                }

            </td>
        </tr>
    }

</table>

TaskManagement/Views/Projects/ListOfSuccessesWithId.cshtml
@model TaskManagement.ViewModels.ProjectViewModel


@{
    ViewBag.Title = "ListOfSuccessesWithId";
}

<h2>ListSuccessesWithId</h2>

<div>
    <h4></h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Project code:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.ProjectCode)
        </dd>

        <dt>
            Project name:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Project.ProjectName)
        </dd>

        <dt>
            Progress (%):
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Progress) %
        </dd>

    </dl>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>