TaskManagement/Controllers/TasksController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TaskManagement.Buisness;
using TaskManagement.Models;
using TaskManagement.ViewModels;

namespace TaskManagement.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public TasksController()
        {

        }
        public TasksController(ApplicationUserManager userManager)
        {
            _userManager = userManager;
        }
        [Authorize(Roles = "Administrator, Project Manager, Developer")]
        public ActionResult Index()
        {
            var currentUserId = User.Identity.GetUserId();
            var isAdministrator = UserManager.GetRoles(currentUserId).Contains("Administrator");
            var tasksList = new List<Tasks>();
            if (isAdministrator)
            {
                tasksList = DbManager.GetAllTasks();
            }
            else
            {
                tasksList = DbManager.GetTasksForUser(currentUserId);
            }
            return View(tasksList);
        }



        [Authorize(Roles = "Administrator")]
        public ActionResult AssignTask()
        {

            //List of all tasks and users is sent to View
            ViewBag.Id = new SelectList(DbManager.GetAllTasks(), "Id", "Description");
            ViewBag.UserId = new SelectList(UserManager.Users.ToList(), "Id", "UserName");

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult AssignTask(Tasks tasks)
        {


            if (ModelState.IsValid)
            {

                DbManager.EditTask(tasks);
                return RedirectToAction("Index");

            }

            return View(tasks);
        }

        // GET: Tasks/Details/5
        [Authorize(Roles = "Administrator, Project Manager, Developer")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Selecting specific Tasks from DB
            Tasks task = DbManager.GetTaskById(id.Value);

            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // GET: Tasks/Create
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Create()
        {
            var currentUserId = User.Identity.GetUserId();
            var rolesList = new List<string>();
            rolesList.Add("Developer");
            if (UserManager.GetRoles(currentUserId).Contains("Administrator"))
            {
                rolesList.Add("Project Manager");
            }

            var projectsList = DbManager.GetProjectsSelectList();
            var statusesList = DbManager.GetStatusSelectList();
            var usersList = DbManager.GetUsersSelectList(rolesList);

            var viewModel = new TaskViewModel(projectsList, statusesList, usersList);

            return View(viewModel);
        }


        // POST: Tasks/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Project Manager")]
        public ActionResult Create(TaskViewModel taskViewModel)
        {
            //checking if user has more than 3 tasks
            var userId = taskViewModel.Task.UserId;
            var count = DbManager.GetNumberOfTasksOfUser(userId);
            if (count > 3)
            {
                ModelState.AddModelError("Task.UserId", "Select another assigne! This one has 3 tasks assigned!");
            }

            if (ModelState.IsValid)
            {
                //on task creating, we are setting task status: new
                taskViewModel.Task.StatusId = (int) Statuses.New;
                DbManager.AddTask(taskViewModel.Task);
                return RedirectToAction("Index");

            }


            var currentUserId = User.Identity.GetUserId();
            var rolesList = new List<string>();
            rolesList.Add("Developer");
            if (UserManager.GetRoles(currentUserId).Contains("Administrator"))
            {
                rolesList.Add("Project Manager");
            }

            taskViewModel.ProjectsSelectList = DbManager.GetProjectsSelectList();
            taskViewModel.StatusesSelectList = DbManager.GetStatusSelectList();
            taskViewModel.UsersSelectList = DbManager.GetUsersSelectList(rolesList);
            return View(taskViewModel);
        }

        // GET: Tasks/Edit/5
        [Authorize(Roles = "Administrator, Project Manager, Developer")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var currentUserId = User.Identity.GetUserId();
            var rolesList = new List<string>();
            rolesList.Add("Developer");
            if (UserManager.GetRoles(currentUserId).Contains("Administrator"))
            {
                rolesList.Add("Project Manager");
            }

            var task = DbManager.GetTaskById(id.Value);
            var projectsList = DbManager.GetProjectsSelectList();
            var statusesList = DbManager.GetStatusSelectList();
            var usersList = DbManager.GetUsersSelectList(rolesList);

            var viewModel = new TaskViewModel(task, projectsList, statusesList, usersList);

            return View(viewModel);
        }

        // POST: Tasks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Project Manager, Developer")]
        public ActionResult Edit(TaskViewModel taskViewModel)
        {
            //checking if user has more than 3 tasks
            var userId = taskViewModel.Task.UserId;
            var count = DbManager.GetNumberOfTasksOfUser(userId);
            if (count > 3)
            {
                ModelState.AddModelError("Task.UserId", "Select another assigne! This one has 3 tasks assigned!");
            }

            if (ModelState.IsValid)
            {
                DbManager.EditTask(taskViewModel.Task);
                return RedirectToAction("Index");
            }

            var currentUserId = User.Identity.GetUserId();
            var rolesList = new List<string>();
            rolesList.Add("Developer");
            if (UserManager.GetRoles(currentUserId).Contains("Administrator"))
            {
                rolesList.Add("Project Manager");
            }

            taskViewModel.ProjectsSelectList = DbManager.GetProjectsSelectList();
            taskViewModel.StatusesSelectList = DbManager.GetStatusSelectList();
            taskViewModel.UsersSelectList = DbManager.GetUsersSelectList(rolesList);
            return View(taskViewModel);
        }

        // GET: Tasks/Delete/5
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Selecting specific task from DB
            Tasks task = DbManager.GetTaskById(id.Value);

            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        // POST: Tasks/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(Tasks task)
        {
            //Selecting specific task and removing it from DB
            DbManager.DeleteTask(task);
            return RedirectToAction("Index");
        }




    }
}

TaskManagement/Controllers/UsersController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TaskManagement.Buisness;
using TaskManagement.Models;
using TaskManagement.ViewModels;

namespace TaskManagement.Controllers
{
    [Authorize]
    public class UsersController : Controller
    {

        [Authorize(Roles = "Administrator")]
        public ActionResult Index()
        {

            //Selecting all users from DB and passing it to View
            var users = DbManager.GetUsers();
            return View(users);
        }


        [Authorize(Roles = "Administrator")]
        public ActionResult AssignRole(string userId, string username)
        {

            if (userId.Equals(""))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var currentRole = DbManager.GetRoleByUserId(userId);

            var rolesSelectList = DbManager.GetRolesSelectList();

            var viewModel = new AssignRoleViewModel(currentRole, rolesSelectList, userId, username);

            return View(viewModel);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult AssignRole(AssignRoleViewModel viewModel)
        {
            if (viewModel.CurrentRole != viewModel.NewRole)
            {
                DbManager.ChangeRoleOfUser(viewModel.UserId, viewModel.CurrentRole, viewModel.NewRole);
            }
            return RedirectToAction("Index");
        }




        [Authorize(Roles = "Administrator")]
        public ActionResult Details(string id)
        {

            if (id.Equals(""))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Selecting specific user from DB
            var user = DbManager.GetUserById(id);

            var role = DbManager.GetRoleByUserId(id);

            //Passing role name to ViewBag.Role 
            ViewBag.Role = role;


            if (user.Equals(null))
            {
                return HttpNotFound();
            }

            return View(user);
        }

        //Delete function is similar to Details
        //Passing same arguments to View
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(string id)
        {

            if (id.Equals(""))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Selecting specific user from DB
            var user = DbManager.GetUserById(id);

            var role = DbManager.GetRoleByUserId(id);

            //Passing role name to ViewBag.Role 
            ViewBag.Role = role;

            if (user.Equals(null))
            {
                return HttpNotFound();
            }
            return View(user);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(ApplicationUser user)
        {
            DbManager.DeleteUser(user);
            return RedirectToAction("Index");
        }


        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(string id)
        {
            if (id.Equals(""))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Selecting specific user from DB
            var user = DbManager.GetUserById(id);

            if (user.Equals(null))
            {
                return HttpNotFound();
            }

            return View(user);
        }


        // POST: Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(ApplicationUser user)
        {
            var u = DbManager.GetUserByUserName(user.UserName);

            if (u != null)
            {
                ModelState.AddModelError("UserName", "This user name allready exists!");
            }
            if (ModelState.IsValid)
            {

                DbManager.EditUser(user);
                return RedirectToAction("Index");

            }

            return View(user);

        }

        // GET: Users/Create
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            var rolesSelectList = DbManager.GetRolesSelectList();

            var viewModel = new UserViewModel(rolesSelectList);

            return View(viewModel);
        }

        // POST: Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(UserViewModel userViewModel)
        {
            var u = DbManager.GetUserByUserName(userViewModel.UserName);

            if (u != null)
            {
                ModelState.AddModelError("UserName", "This user name allready exists!");
            }

            if (ModelState.IsValid)
            {
                var user = new ApplicationUser() {
                    Email = userViewModel.Email, 
                    FirstName = userViewModel.FirstName,
                    SurName = userViewModel.SurName,
                    UserName = userViewModel.UserName
                };

                DbManager.AddUser(user, userViewModel.Password, userViewModel.RoleName);
                return RedirectToAction("Index");
                

            }
            var rolesSelectList = DbManager.GetRolesSelectList();
            userViewModel.RolesSelectList = rolesSelectList;
            return View(userViewModel);
        }


    }
}

TaskManagement/Views/Shared/_DeveloperTaskEditPartial.cshtml
@model TaskManagement.Models.Tasks


<div class="form-group">
    @Html.LabelFor(model => model.Progress, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Progress, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Progress, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
    </div>
</div>

TaskManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Task Management", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @if (User.IsInRole("Administrator") || User.IsInRole("Project Manager")) {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Manage projects <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Create project", "Create", "Projects")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("List of projects", "Index", "Projects")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Manage tasks<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Create task", "Create", "Tasks")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("List of tasks", "Index", "Tasks")</li>
                            </ul>
                        </li>
                    }
                    @if (User.IsInRole("Developer")) {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Manage tasks<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("List of tasks", "Index", "Tasks")</li>
                            </ul>
                        </li>
                    }

                    @if (User.IsInRole("Administrator")) {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Manage users<span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li>@Html.ActionLink("Create user", "Create", "Users")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("List of users", "Index", "Users")</li>
                            </ul>
                        </li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Task Management</p>
        </footer>
    </div>

  
</body>
</html>

TaskManagement/Views/Shared/_ManagerTaskEditPartial.cshtml
@model TaskManagement.Models.Tasks


<div class="form-group">
    @Html.LabelFor(model => model.Progress, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Progress, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Progress, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Deadline, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class='col-md-10'>
        @Html.TextBoxFor(model => model.Deadline, new { @class = "form-control", @id = "datetimepicker2" })
    </div>
    @Html.ValidationMessageFor(model => model.Deadline)
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.StatusId, "StatusId", htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
    </div>
</div>